<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl = "http://www.w3.org/1999/XSL/Transform" xmlns:xalan = "http://xml.apache.org/xalan" xmlns:rcfa = "http://xml.amadeus.com/RCFARQ_05_2_1A" 
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" exclude-result-prefixes = "xalan" version = "1.0">
    <xsl:template name = "Car_RateInformationFromAvailability_Dynamic">
        <xsl:param name = "currencyCodePOSU_para"/>
                <xsl:variable name = "pickuplocation">
                    <xsl:value-of select = "/soapenv:Envelope/soapenv:Body/rcfa:Car_RateInformationFromAvailability/rcfa:pickupDropoffLocs[1]/rcfa:locationDescription/rcfa:name"/>
                </xsl:variable>
                <xsl:variable name = "dropofflocation">
                    <xsl:value-of select = "/soapenv:Envelope/soapenv:Body/rcfa:Car_RateInformationFromAvailability/rcfa:pickupDropoffLocs[2]/rcfa:locationDescription/rcfa:name"/>
                </xsl:variable>
                <xsl:variable name = "vendorCode">
                    <xsl:value-of select = "/soapenv:Envelope/soapenv:Body/rcfa:Car_RateInformationFromAvailability/rcfa:companyDetails/rcfa:companyCode"/>
                </xsl:variable>
                <xsl:variable name = "SIPP">
                    <xsl:value-of select = "/soapenv:Envelope/soapenv:Body/rcfa:Car_RateInformationFromAvailability/rcfa:vehicleInformation/rcfa:vehicleRentalNeedType/rcfa:vehicleRentalPrefType"/>
                </xsl:variable>
					<xsl:param name = "roundTripBoolean">
            			<xsl:choose>
                			<xsl:when test = "$pickuplocation=$dropofflocation">1</xsl:when>
                			<xsl:otherwise>0</xsl:otherwise>
            			</xsl:choose>
        			</xsl:param>
        <Car_RateInformationFromAvailabilityReply xmlns = "http://xml.amadeus.com/RCFARR_10_1_1A">
            <rateDetails>
                <companyIdentification>
                    <travelSector>CAR</travelSector>
                    <companyCode><xsl:value-of select = "$vendorCode"/></companyCode>
                    <companyName>HERTZ</companyName>
                    <accessLevel>CP</accessLevel>
                </companyIdentification>
                <sourceLevel>
                    <selectionDetails>
                        <option>P6</option>
                    </selectionDetails>
                </sourceLevel>
                <rateDetail>
                    <tariffInfo>
                        <amount><xsl:value-of select = "document('.\uAPI\CarPrices.xml')/CarPrice/Car[@RoundTripBoolean=$roundTripBoolean and @SIPP=$SIPP and @PackageBoolean='0']/@BaseRate"/></amount>
                        <currency><xsl:value-of select = "$currencyCodePOSU_para"/></currency>
                        <ratePlanIndicator>WD</ratePlanIndicator>
                        <amountType>RP</amountType>
                        <rateChangeIndicator>GUA</rateChangeIndicator>
                    </tariffInfo>
                    <chargeDetails>
                        <type>034</type>
                        <description>UNL</description>
                    </chargeDetails>
                    <chargeDetails>
                        <type>008</type>
                        <amount>130.88</amount>
                    </chargeDetails>
                    <chargeDetails>
                        <type>80</type>
                        <description>UNL</description>
                    </chargeDetails>
                    <chargeDetails>
                        <type>108</type>
                        <comment>VEH LIC COST RECVRY</comment>
                    </chargeDetails>
                    <chargeDetails>
                        <type>108</type>
                        <comment>AIRPORT FEE</comment>
                    </chargeDetails>
                    <chargeDetails>
                        <type>COV</type>
                        <comment>TP - THEFT PROTECTION</comment>
                    </chargeDetails>
                    <chargeDetails>
                        <type>COV</type>
                        <comment>CDW - COLLISION DAMAGE WAIVER</comment>
                    </chargeDetails>
                    <chargeDetails>
                        <type>045</type>
                        <amount>52.50</amount>
                        <comment>TAX</comment>
                    </chargeDetails>
                </rateDetail>
                <rateDetail>
                    <tariffInfo>
                        <amount><xsl:value-of select = "document('.\uAPI\CarPrices.xml')/CarPrice/Car[@RoundTripBoolean=$roundTripBoolean and @SIPP=$SIPP and @PackageBoolean='0']/@BaseRateTotal"/></amount>
                        <currency><xsl:value-of select = "$currencyCodePOSU_para"/></currency>
                        <amountType>RB</amountType>
                    </tariffInfo>
                    <chargeDetails>
                        <type>NBD</type>
                        <amount>2</amount>
                    </chargeDetails>
                </rateDetail>
                <rateDetail>
                    <tariffInfo>
                        <amount><xsl:value-of select = "document('.\uAPI\CarPrices.xml')/CarPrice/Car[@RoundTripBoolean=$roundTripBoolean and @SIPP=$SIPP and @PackageBoolean='0']/@TotalRate"/></amount>
                        <currency><xsl:value-of select = "$currencyCodePOSU_para"/></currency>
                        <amountType>904</amountType>
                    </tariffInfo>
                </rateDetail>
                <dummy/>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>108</type>
                            <amount>0.00</amount>
                            <description>IBR</description>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                            <comment>VEH LIC COST RECVRY</comment>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>108</type>
                            <amount>0.00</amount>
                            <description>IBR</description>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                            <comment>AIRPORT FEE</comment>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>COV</type>
                            <amount>0.00</amount>
                            <description>IBR</description>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                            <comment>TP - THEFT PROTECTION</comment>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>COV</type>
                            <amount>0.00</amount>
                            <description>IBR</description>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                            <comment>CDW - COLLISION DAMAGE WAIVER</comment>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>COV</type>
                            <amount>8.32</amount>
                            <description>OPT</description>
                            <periodType>001</periodType>
                            <currency>EUR</currency>
                            <comment>PAE - PERSONAL ACCIDENT AND EFFECTS COVER</comment>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>COV</type>
                            <amount>23.32</amount>
                            <description>OPT</description>
                            <periodType>001</periodType>
                            <currency>EUR</currency>
                            <comment>COV - SUP  - SUPER COVER</comment>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>013</type>
                            <description>OPT</description>
                            <comment>CBS - PREMIUM EMERGENCY ROADSIDE ASSISTANCE</comment>
                        </chargeDetails>
                        <chargeDetails>
                            <type>013</type>
                            <amount>13.20</amount>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>013</type>
                            <description>OPT</description>
                            <comment>CST - CHILD SEAT FOR TODDLER</comment>
                        </chargeDetails>
                        <chargeDetails>
                            <type>013</type>
                            <amount>46.20</amount>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>013</type>
                            <description>OPT</description>
                            <comment>CSI - CHILD SEAT FOR INFANT</comment>
                        </chargeDetails>
                        <chargeDetails>
                            <type>013</type>
                            <amount>46.20</amount>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>013</type>
                            <description>OPT</description>
                            <comment>NVS - NAVIGATIONAL SYSTEM</comment>
                        </chargeDetails>
                        <chargeDetails>
                            <type>013</type>
                            <amount>39.96</amount>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>013</type>
                            <description>OPT</description>
                            <comment>MMS - MULTI MEDIA CENTER</comment>
                        </chargeDetails>
                        <chargeDetails>
                            <type>013</type>
                            <amount>23.98</amount>
                            <periodType>004</periodType>
                            <currency>EUR</currency>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <taxCovSurchargeGroup>
                    <taxSurchargeCoverageInfo>
                        <tariffInfo>
                            <currency>EUR</currency>
                        </tariffInfo>
                        <chargeDetails>
                            <type>045</type>
                            <amount>20.00</amount>
                            <description>IES</description>
                            <periodType>012</periodType>
                            <comment>TAX</comment>
                        </chargeDetails>
                    </taxSurchargeCoverageInfo>
                </taxCovSurchargeGroup>
                <vehicleInfoGroup>
                    <vehicleDetails>
                        <vehicleCharacteristic>
                            <vehicleTypeOwner>ACR</vehicleTypeOwner>
                            <vehicleRentalPrefType><xsl:value-of select = "$SIPP"/></vehicleRentalPrefType>
                        </vehicleCharacteristic>
                        <freeTextDetails>
                            <textSubjectQualifier>3</textSubjectQualifier>
                            <informationType>SI</informationType>
                            <companyId>1A</companyId>
                            <encoding>1</encoding>
                        </freeTextDetails>
                        <carModel>G PEUGEOT 508 SW AUTO OR SIMILAR</carModel>
                    </vehicleDetails>
                </vehicleInfoGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MIN</qualifier>
                            <daysOfOperation>01</daysOfOperation>
                        </ruleDetails>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MAX</qualifier>
                        </ruleDetails>
                    </otherRules>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MIN</qualifier>
                            <daysOfOperation>02</daysOfOperation>
                        </ruleDetails>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MAX</qualifier>
                        </ruleDetails>
                    </otherRules>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MIN</qualifier>
                            <daysOfOperation>03</daysOfOperation>
                        </ruleDetails>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MAX</qualifier>
                        </ruleDetails>
                    </otherRules>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MIN</qualifier>
                            <daysOfOperation>04</daysOfOperation>
                        </ruleDetails>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MAX</qualifier>
                        </ruleDetails>
                    </otherRules>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MIN</qualifier>
                            <daysOfOperation>05</daysOfOperation>
                        </ruleDetails>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MAX</qualifier>
                        </ruleDetails>
                    </otherRules>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MIN</qualifier>
                            <daysOfOperation>06</daysOfOperation>
                        </ruleDetails>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MAX</qualifier>
                        </ruleDetails>
                    </otherRules>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantity>1</quantity>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MIN</qualifier>
                            <daysOfOperation>07</daysOfOperation>
                        </ruleDetails>
                        <ruleDetails>
                            <type>PCK</type>
                            <quantityUnit>3</quantityUnit>
                            <qualifier>MAX</qualifier>
                        </ruleDetails>
                    </otherRules>
                    <dateTimeInfo>
                        <businessSemantic>PKT</businessSemantic>
                        <beginDateTime>
                            <hour>7</hour>
                            <minutes>0</minutes>
                        </beginDateTime>
                        <endDateTime>
                            <hour>23</hour>
                            <minutes>59</minutes>
                        </endDateTime>
                    </dateTimeInfo>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>OWI</type>
                            <qualifier>005</qualifier>
                        </ruleDetails>
                    </otherRules>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>ADB</type>
                            <quantity>1</quantity>
                            <quantityUnit>002</quantityUnit>
                        </ruleDetails>
                    </otherRules>
                </otherRulesGroup>
                <otherRulesGroup>
                    <otherRules>
                        <ruleDetails>
                            <type>GUA</type>
                            <quantity>365</quantity>
                            <quantityUnit>3</quantityUnit>
                        </ruleDetails>
                        <ruleText>
                            <textType>GUA</textType>
                            <freeText>RATE GUARANTEED 365 DAYS FROM BOOKING</freeText>
                        </ruleText>
                    </otherRules>
                    <dateTimeInfo>
                        <businessSemantic>BED</businessSemantic>
                        <beginDateTime>
                            <year>2014</year>
                            <month>5</month>
                            <day>19</day>
                        </beginDateTime>
                        <endDateTime>
                            <year>2015</year>
                            <month>5</month>
                            <day>19</day>
                        </endDateTime>
                    </dateTimeInfo>
                </otherRulesGroup>
                <pickupDropoffLocation>
                    <locationCode>
                        <locationType>176</locationType>
                        <locationDescription>
                            <code>1A</code>
                            <name><xsl:value-of select = "$pickuplocation"/></name>
                        </locationDescription>
                    </locationCode>
                    <address>
                        <addressDetails>
                            <format>5</format>
                            <line1>AEROPORT DE SAINT EXUPERY</line1>
                        </addressDetails>
                        <city>LYON 69125</city>
                        <countryCode>FR</countryCode>
                    </address>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                        <beginDateTime>
                            <hour>7</hour>
                            <minutes>0</minutes>
                        </beginDateTime>
                        <endDateTime>
                            <hour>23</hour>
                            <minutes>0</minutes>
                        </endDateTime>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <phone>
                        <phoneOrEmailType>PHO</phoneOrEmailType>
                        <telephoneNumber>
                            <telephoneNumber>0825006969</telephoneNumber>
                        </telephoneNumber>
                    </phone>
                </pickupDropoffLocation>
                <pickupDropoffLocation>
                    <locationCode>
                        <locationType>DOL</locationType>
                        <locationDescription>
                            <code>1A</code>
                            <name><xsl:value-of select = "$dropofflocation"/></name>
                        </locationDescription>
                    </locationCode>
                    <address>
                        <addressDetails>
                            <format>5</format>
                            <line1>AEROPORT DE SAINT EXUPERY</line1>
                        </addressDetails>
                        <city>LYON 69125</city>
                        <countryCode>FR</countryCode>
                    </address>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                    <openingHours>
                        <businessSemantic>OCH</businessSemantic>
                    </openingHours>
                </pickupDropoffLocation>
                <rateCodeGroup>
                    <rateCode>
                        <fareCategories>
                            <fareType>EOW1GB</fareType>
                        </fareCategories>
                    </rateCode>
                    <additionalInfo>
                        <freeTextDetails>
                            <textSubjectQualifier>3</textSubjectQualifier>
                            <informationType>SI</informationType>
                            <companyId>1A</companyId>
                            <encoding>1</encoding>
                        </freeTextDetails>
                        <freeText>WEEKEND INCLUSIVE</freeText>
                    </additionalInfo>
                </rateCodeGroup>
            </rateDetails>
        </Car_RateInformationFromAvailabilityReply>
    </xsl:template>
</xsl:stylesheet>
