<?xml version="1.0"?>
<xsl:stylesheet
    xmlns:xsl = "http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan = "http://xml.apache.org/xalan"
    xmlns:pnra = "http://xml.amadeus.com/PNRADD_11_1_1A"
    xmlns:soapenv = "http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:ama="http://xml.amadeus.com/2010/06/Security_v1"
    exclude-result-prefixes = "xalan"
    version = "1.0">
    <xsl:template name = "PNR_AddElements_Dynamic_0">
		<xsl:variable name = "officeID">
                <xsl:value-of select = "/soapenv:Envelope/soapenv:Header/ama:AMA_SecurityHostedUser/ama:UserID/@ama:PseudoCityCode"/>
            </xsl:variable>
        <PNR_Reply xmlns = "http://xml.amadeus.com/PNRACC_11_1_1A">            
            <pnrHeader>
                <reservationInfo>
                    <reservation>
                        <companyId>1A</companyId>
                    </reservation>
                </reservationInfo>
            </pnrHeader>
            <securityInformation>
                <responsibilityInformation>
                    <typeOfPnrElement>RP</typeOfPnrElement>
                    <officeId>        <xsl:value-of select = "$officeID"/></officeId>
                    <iataCode>20263051</iataCode>
                </responsibilityInformation>
                <queueingInformation>
                    <queueingOfficeId><xsl:value-of select = "$officeID"/></queueingOfficeId>
                </queueingInformation>
                <cityCode>PAR</cityCode>
            </securityInformation>
            <sbrPOSDetails>
                <sbrUserIdentificationOwn>
                    <originIdentification>
                        <inHouseIdentification1></inHouseIdentification1>
                    </originIdentification>
                </sbrUserIdentificationOwn>
                <sbrSystemDetails>
                    <deliveringSystem>
                        <companyId></companyId>
                    </deliveringSystem>
                </sbrSystemDetails>
                <sbrPreferences>
                    <userPreferences>
                        <codedCountry></codedCountry>
                    </userPreferences>
                </sbrPreferences>
            </sbrPOSDetails>
            <sbrCreationPosDetails>
                <sbrUserIdentificationOwn>
                    <originIdentification>
                        <inHouseIdentification1></inHouseIdentification1>
                    </originIdentification>
                </sbrUserIdentificationOwn>
                <sbrSystemDetails>
                    <deliveringSystem>
                        <companyId></companyId>
                    </deliveringSystem>
                </sbrSystemDetails>
                <sbrPreferences>
                    <userPreferences>
                        <codedCountry></codedCountry>
                    </userPreferences>
                </sbrPreferences>
            </sbrCreationPosDetails>
            <sbrUpdatorPosDetails>
                <sbrUserIdentificationOwn>
                    <originIdentification>
                        <originatorId>20263051</originatorId>
                        <inHouseIdentification1><xsl:value-of select = "$officeID"/></inHouseIdentification1>
                    </originIdentification>
                    <originatorTypeCode>T</originatorTypeCode>
                </sbrUserIdentificationOwn>
                <sbrSystemDetails>
                    <deliveringSystem>
                        <companyId>1A</companyId>
                        <locationId>PAR</locationId>
                    </deliveringSystem>
                </sbrSystemDetails>
                <sbrPreferences>
                    <userPreferences>
                        <codedCountry>FR</codedCountry>
                    </userPreferences>
                </sbrPreferences>
            </sbrUpdatorPosDetails>
            <travellerInfo>
                <elementManagementPassenger>
                    <reference>
                        <qualifier>PT</qualifier>
                        <number>2</number>
                    </reference>
                    <segmentName>NM</segmentName>
                    <lineNumber>1</lineNumber>
                </elementManagementPassenger>
                <passengerData>
                    <travellerInformation>
                        <traveller>
                            <surname>STTWO</surname>
                            <quantity>1</quantity>
                        </traveller>
                        <passenger>
                            <firstName>CARBSRESERVE</firstName>
                        </passenger>
                    </travellerInformation>
                </passengerData>
            </travellerInfo>
            <dataElementsMaster>
                <marker2></marker2>
                <dataElementsIndiv>
                    <elementManagementData>
                        <segmentName>RF</segmentName>
                    </elementManagementData>
                    <otherDataFreetext>
                        <freetextDetail>
                            <subjectQualifier>3</subjectQualifier>
                            <type>P22</type>
                        </freetextDetail>
                        <longFreetext>PAREC38EE</longFreetext>
                    </otherDataFreetext>
                </dataElementsIndiv>
                <dataElementsIndiv>
                    <elementManagementData>
                        <reference>
                            <qualifier>OT</qualifier>
                            <number>1</number>
                        </reference>
                        <segmentName>AP</segmentName>
                        <lineNumber>2</lineNumber>
                    </elementManagementData>
                    <otherDataFreetext>
                        <freetextDetail>
                            <subjectQualifier>3</subjectQualifier>
                            <type>3</type>
                        </freetextDetail>
                        <longFreetext>1425555-5555</longFreetext>
                    </otherDataFreetext>
                </dataElementsIndiv>
                <dataElementsIndiv>
                    <elementManagementData>
                        <reference>
                            <qualifier>OT</qualifier>
                            <number>2</number>
                        </reference>
                        <segmentName>TK</segmentName>
                        <lineNumber>3</lineNumber>
                    </elementManagementData>
                    <ticketElement>
                        <passengerType>PAX</passengerType>
                        <ticket>
                            <indicator>OK</indicator>
                            <date>091116</date>
                            <officeId><xsl:value-of select = "$officeID"/></officeId>
                        </ticket>
                    </ticketElement>
                </dataElementsIndiv>
            </dataElementsMaster>
        </PNR_Reply>
    </xsl:template>
    <xsl:template name = "PNR_AddElements_Dynamic_10">
<PNR_Reply xmlns="http://xml.amadeus.com/PNRACC_11_1_1A">
			<pnrHeader>
				<reservationInfo>
					<reservation>
						<companyId>1A</companyId>
						<controlNumber>7H2XEI</controlNumber>
					</reservation>
				</reservationInfo>
			</pnrHeader>
			<securityInformation>
				<responsibilityInformation>
					<typeOfPnrElement>RP</typeOfPnrElement>
				</responsibilityInformation>
			</securityInformation>
			<sbrPOSDetails>
				<sbrUserIdentificationOwn>
					<originIdentification>
						<inHouseIdentification1></inHouseIdentification1>
					</originIdentification>
				</sbrUserIdentificationOwn>
			</sbrPOSDetails>
			<sbrCreationPosDetails>
				<sbrUserIdentificationOwn>
					<originIdentification>
						<inHouseIdentification1></inHouseIdentification1>
					</originIdentification>
				</sbrUserIdentificationOwn>
			</sbrCreationPosDetails>
			<sbrUpdatorPosDetails>
				<sbrUserIdentificationOwn>
					<originIdentification>
						<inHouseIdentification1></inHouseIdentification1>
					</originIdentification>
				</sbrUserIdentificationOwn>
			</sbrUpdatorPosDetails>
			<originDestinationDetails>
				<originDestination></originDestination>
			</originDestinationDetails>
			<dataElementsMaster>
				<marker2></marker2>
			</dataElementsMaster>
		</PNR_Reply>
</xsl:template>
</xsl:stylesheet>
